# https://stackoverflow.com/questions/59518658/how-to-use-github-release-version-number-in-github-action
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/events-that-trigger-workflows#release-event-release
# https://help.github.com/en/actions/reference/events-that-trigger-workflows#release-event-release
# https://help.github.com/en/actions/configuring-and-managing-workflows/persisting-workflow-data-using-artifacts#passing-data-between-jobs-in-a-workflow

name: Build and release changelog if tagged

on: push

jobs:
  build:
    if: github.event_name == 'push' && contains(toJson(github.event.commits), '***NO_CI***') == false && contains(toJson(github.event.commits), '[ci skip]') == false && contains(toJson(github.event.commits), '[skip ci]') == false

    runs-on: ubuntu-latest

    env:
      MYSQL_USER: root
      MYSQL_DB: temp
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root

    # Docs: https://docs.github.com/en/actions/using-containerized-services
    # https://github.com/shivammathur/setup-php/blob/master/examples/cakephp-mysql.yml
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: ${{ env.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ env.MYSQL_DB }}
          MYSQL_USER: ${{ env.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ env.MYSQL_PASSWORD }}
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    # check out the repository, so the workflow can access it
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Install Node
      uses: actions/setup-node@v2
      with:
        node-version: '18.7.0'
    
    # MAMP Pro uses 7.2.20
    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.2.15'

    # Downgrade from Composer 2 in ubuntu-latest, to Composer 1, as v2 causes issues
    # https://github.com/actions/virtual-environments/issues/1816
    # Fix: https://github.com/actions/virtual-environments/issues/1924
    - name: Make sure we are using composer v1
      run: |
        sudo composer self-update --1
        sudo chown $USER $HOME/.composer

    # https://github.com/cypress-io/github-action#install-cypress-only
    - name: Cache dependencies
      uses: actions/cache@v2
      id: cache
      with:
        path: |
          ~/.cache
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

    - name: Composer config
      run: |
        composer config -g github-oauth.github.com ${{ secrets.GH_TOKEN }}

    - name: Install dependencies
      run: |
        npm ci

    # - name: Run linting
    #   run: |
    #     npm run lint:internal --if-present

    - name: Run Mocha tests, which in turn run test:js (Cypress tests) and test (WordPress/PHP tests)
      run: |
        mysql --host=127.0.0.1 --user=${{ env.MYSQL_USER }} --password=${{ env.MYSQL_PASSWORD }} ${{ env.MYSQL_DB }}
        npm run test:internal --if-present
      env:
        WPUNIT_DB_USER: ${{ env.MYSQL_USER }}
        WPUNIT_DB_PASS: ${{ env.MYSQL_PASSWORD }}
        WPUNIT_DB_HOST: 127.0.0.1

    # TODO Reenable once CI issues resolved
    # - name: Archive changelog
    #   uses: actions/upload-artifact@v1
    #   with:
    #     name: changelog
    #     path: CHANGELOG.md

  # The 'release' job starts with a clean directory,
  # we don't check out the repo again
  # instead we download and work with
  # the artifacts from the previous 'build' job
  # TODO Reenable once CI issues resolved
  # release:
  #   runs-on: ubuntu-latest
  #   needs: build

  #   # https://stackoverflow.com/a/58869470/6850747
  #   # https://help.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-output-parameter
  #   steps:
  #   - name: Check Tag
  #     id: check-tag
  #     run: |
  #       if [[ ${{ github.event.ref }} =~ ^refs\/tags\/[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
  #         echo ::set-output name=match::true
  #       fi

  #   - name: Download changelog from Build
  #     if: steps.check-tag.outputs.match == 'true'
  #     uses: actions/download-artifact@v2
  #     with:
  #       name: changelog
  #       path: changelog

  #   - name: Check that artifacts were downloaded as expected
  #     run: ls -R

  #   - name: Upload changelog to the repository's Releases page
  #     if: steps.check-tag.outputs.match == 'true'
  #     uses: yakuhzi/action-release@v1
  #     with:
  #       changelog: changelog/CHANGELOG.md
  #     env:
  #       GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  

