# https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
# https://help.github.com/en/actions/configuring-and-managing-workflows/using-environment-variables

name: Build

on: push

jobs:
  build:
    if: github.event_name == 'push' && contains(toJson(github.event.commits), '***NO_CI***') == false && contains(toJson(github.event.commits), '[ci skip]') == false && contains(toJson(github.event.commits), '[skip ci]') == false

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
    # check out the repository, so the workflow can access it
    - name: Checkout repo
      uses: actions/checkout@v2
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.2.15'
        node-version: ${{ matrix.node-version }}
  
    - name: Run tests 
      run: |
        composer config -g github-oauth.github.com ${{ secrets.GH_PAT_WPDTRT_DBTH }}
        npm run test:internal
      env:
        WPUNIT_DB_USER: root
        WPUNIT_DB_PASS: root
        WPUNIT_DB_HOST: localhost
