# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # check out the repository, so the workflow can access it
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Install Node
      uses: actions/setup-node@v2
      with:
        node-version: '18.7.0'
    
    # MAMP Pro uses 7.2.20
    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.2.15'

    # Downgrade from Composer 2 in ubuntu-latest, to Composer 1, as v2 causes issues
    # https://github.com/actions/virtual-environments/issues/1816
    # Fix: https://github.com/actions/virtual-environments/issues/1924
    - name: Make sure we are using composer v1
      run: |
        sudo composer self-update --1
        sudo chown $USER $HOME/.composer

    # Fix Cypress cannot write to the cache directory due to file permissions
    # https://github.com/cypress-io/cypress/issues/1281
    - name: Grant Cypress permission to download to cache directory
      run: |
        sudo chown $USER $HOME/.cache
    
    # https://github.com/cypress-io/github-action#install-cypress-only
    - name: Cache dependencies
      uses: actions/cache@v2
      id: cache
      with:
        path: |
          ~/.cache
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

    - name: Composer config
      run: |
        composer config -g github-oauth.github.com ${{ secrets.GITHUB_TOKEN }}

    - name: Install dependencies
      run: |
        npm ci

    - name: Get env values
      run: |
        echo env${{ runner.temp }}

    - name: Run pretest
      run: |
        npm run pretest